### ISSUE TITLE
Help command, Next page not working

### ISSUE THREAD

**Issue by dh2-io** [ScootKit/CustomDCBot#116]
Sooo, i installed the bot and enabled some modules, but i they aren´t configured yet.
And when i try to use the /help command and press on the "next" button, the bot crashes and i get this error

### Info:
OS: Ubuntu 22.04
Node version: v18.16.0
Version of the Bot: [v3.7.0](https://github.com/ScootKit/CustomDCBot/releases/tag/v3.7.0)

### How to reproduce:
- Start the bot
- use the /help cmd in discord 
- ![Discord Help](https://i.dh2.io/paRo3/KAfIzExe98.png/raw) 
- press on the "Next" Button 
- ![Next Button](https://i.dh2.io/paRo3/cibupetE32.png/raw)
- Get Error 
- ![Errrrrrrrooooorrrr](https://i.dh2.io/paRo3/SoRIgega78.png/raw)

```
[INFO] Done with checking. Out of 39 modules, 16 were enabled, 5 were disabled because their configuration was wrong.
[INFO] Guild application commands are up to date - no syncing required
[INFO] Synced global application commands
[INFO] The bot initiated successfully and is now listening to commands
[DEBUG] Dust!n#0666 (515516384999112705) used command /help  
/home/container/node_modules/discord.js/src/client/actions/InteractionCreate.js:48
        if (channel && !channel.isText()) return;
                                ^
TypeError: channel.isText is not a function
    at InteractionCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/InteractionCreate.js:48:33)
    at module.exports [as INTERACTION_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:482:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:317:10)
    at callListener (/home/container/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/home/container/node_modules/ws/lib/websocket.js:1180:20)
    at Receiver.emit (node:events:513:28)
Node.js v18.16.0
```

**Comment by SCDerox** [comment]
Thanks for reaching out - this issue occurs due to an outdated version of discord.js. We haven't updated the open source version of the CustomBot yet (as the Open-Source-Version is currently not our priority). You can either wait for a fix, or update to the newest version of discord.js by running `npm i discord.js@v13-lts` and/or updating the version number manually in your package.json file and reinstalling dependencies.

**Comment by dh2-io** [comment]
Ok, i updated to the latest version of v13 (13.16.0) and now it works just fine
Thx
