### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jahsenn** [ScootKit/CustomDCBot#134]
> customdcbot@3.7.0 start
> node main.js

[INFO] SCNX-CustomBot v2 - Log-Level: DEBUG
[INFO] Missing moduleConfig-file. Automatically disabling all modules and overwriting modules.json later
/home/runner/CustomDCBot/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:55
        throw new Error(`Please install ${moduleName} package manually`);
        ^

Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/home/runner/CustomDCBot/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:55:15)
    at new ConnectionManager (/home/runner/CustomDCBot/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:18:21)
    at new SqliteDialect (/home/runner/CustomDCBot/node_modules/sequelize/lib/dialects/sqlite/index.js:13:30)
    at new Sequelize (/home/runner/CustomDCBot/node_modules/sequelize/lib/sequelize.js:194:20)
    at Object.<anonymous> (/home/runner/CustomDCBot/main.js:98:12)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)

Node.js v20.10.0

**Comment by jateute** [comment]
You need to install the module sqlite3, like the error message already says. And if you have trouble using the bot, you need to open a discussion and not an issue.
