### ISSUE TITLE
Unknown Module

### ISSUE THREAD

**Issue by PBOwner** [ScootKit/CustomDCBot#146]
Trying to start the bot, and i get this: 
```bash
node:internal/modules/cjs/loader:1142
  const err = new Error(message);
              ^

Error: Cannot find module './scnx-integration'
Require stack:
- /root/CustomDCBot/src/functions/configuration.js
- /root/CustomDCBot/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at /root/CustomDCBot/src/functions/configuration.js:83:53
    at new Promise (<anonymous>)
    at checkConfigFile (/root/CustomDCBot/src/functions/configuration.js:61:12)
    at /root/CustomDCBot/src/functions/configuration.js:208:75
    at new Promise (<anonymous>)
    at checkModuleConfig (/root/CustomDCBot/src/functions/configuration.js:204:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/CustomDCBot/src/functions/configuration.js',
    '/root/CustomDCBot/main.js'
  ]
}```
But none of the docs etc state anything about this.

**Comment by PBOwner** [comment]
Turns out, 2 of the modules require it. None of the others
auto-messager and twitch-notifications

**Comment by SCDerox** [comment]
Thanks for opening an issue. This is a [known issue](https://github.com/ScootKit/CustomDCBot/discussions/143#discussioncomment-9885801) and will be fixed in a future version release.

**Comment by PBOwner** [comment]
Besides this, great bot 100%
